### ISSUE TITLE
onBackgroundMessage and onNotificationTap is not working in iOS

### ISSUE THREAD

**Issue by YanaWijaya** [ben-xD/push#14]
My iOS version is 16.4.1, and both onBackgroundMessage and onNotificationTap seem not working.
I've put a logger inside both events, and I'm able to receive the push notifications, but my logger doesn't trigger and the events seem not listening when notifications arrived.

I'm using it on Flutter StatefulWidget, and listening from the initState method.
I'm not using FCM, the BE server send directly to Apple APN service.

Any advice?

Thanks.
![Screenshot 2023-05-29 at 08 30 13](https://github.com/ben-xD/push/assets/112671773/761c7d76-75ab-4043-b1ef-7ee1f023b754)
![Screenshot 2023-05-29 at 10 38 49](https://github.com/ben-xD/push/assets/112671773/ca9c8b5e-1dc3-45ba-9a7b-3d38ad65121f)

**Comment by ben-xD** [comment]
Hi @YanaWijaya, 

Is your widget (the one setting up these listeners) running when the app **starts**, without any user interaction? 

This sounds similar to the reason I explained in https://github.com/ben-xD/push/issues/12#issuecomment-1566183632. Please take a look at let me know.

**Comment by YanaWijaya** [comment]
Hi @ben-xD 

Yes, my widget is running when the app starts and without user interaction.

As per your comment in [this ticket](https://github.com/ben-xD/push/issues/12#issuecomment-1566183632) I've tried to move the listener to higher up in the widget tree, I'm now put it on main.dart, but still no luck.

I've got this message when trying tapping the notification from background state
![Screenshot 2023-05-29 at 18 08 14](https://github.com/ben-xD/push/assets/112671773/952deb9c-3641-4fb0-9360-d21c305bdab4)

Is there any additional step that I need to configure in xcode, apart from turn on the Remote Notifications and Background Fetch capabilities?
![Screenshot 2023-05-29 at 18 18 55](https://github.com/ben-xD/push/assets/112671773/3049c956-a55d-4866-8705-dafaf3e15e1e)


For the example app, is it possible to clone the previous version (0.1.3) ? 
Because the latest version requires me to upgrade my Dart version, if possible I want to avoid updating my Dart version.

Thanks

**Comment by ben-xD** [comment]
Hi @YanaWijaya,

If you want to run the example app, you could `git checkout dbf1cacf3b5ee9f0b81b37d10a4ba92d260d008d` or `git checkout 0.1.3` to get an older version. However, this will probably not work with new versions of Flutter, but since you're using an old version of Dart, you're also on an old version of Flutter.

Just curious, what version of Dart/Flutter are you currently using?

> I'm wondering if there is any additional step that I need to configure in xcode, apart from turning on the Remote Notifications and Background Fetch capabilities?

That's all that's needed :)

**Comment by ben-aw** [comment]
Hi @ben-xD and @YanaWijaya,  I'm having similar issues on iOS, but I receive a `onNotificationTap` on the second time a push notification is tapped.  The first time, the stream never picks it up.  I listen to the stream in the app's `main` method.  I'm also getting `onNewToken` and `onMessage` to work fine the first time.

**Comment by ben-xD** [comment]
Hey @ben-aw, this should be fixed by https://github.com/ben-xD/push/issues/16, available as `1.0.1`.

Can someone report if they see the original issue faced in this ticket? Maybe @YanaWijaya or @danieljiwonkang98?

**Comment by ben-xD** [comment]
I think this is solved so I'll close it. Please reply if you see any existing issues.
