### ISSUE TITLE
RemoteMessage is different for Android and IOS

### ISSUE THREAD

**Issue by chaau** [ben-xD/push#15]
I think I found an issue with RemoteMessage;
Tested both the foreground and background messages:

```dart
 // Handle push notifications
      final onMessageSubscription = Push.instance.onMessage.listen((message) {
        print('RemoteMessage received while app is in foreground:\n'
            'RemoteMessage.Notification: ${message.notification} \n'
            ' title: ${message.notification?.title.toString()}\n'
            ' body: ${message.notification?.body.toString()}\n'
            'RemoteMessage.Data: ${message.data}');
        messagesReceived.value += [message];
        // Push Notifications won't be shown by default when the app is in the foreground.
        // TODO use the state to show local notification.
        if (message.notification != null &&
            isForegroundNotificationsEnabled.value) {
          displayForegroundNotification(message.notification!);
        }
      });
```

```dart
      // Handle push notifications
      final onBackgroundMessageSubscription =
          Push.instance.onBackgroundMessage.listen((message) {
        print('RemoteMessage received while app is in background:\n'
            'RemoteMessage.Notification: ${message.notification} \n'
            ' title: ${message.notification?.title.toString()}\n'
            ' body: ${message.notification?.body.toString()}\n'
            'RemoteMessage.Data: ${message.data}');
        backgroundMessagesReceived.value += [message];
      });
```

Sent a test message via Firebase console

In both cases the "message.notification" is null, it looks like it is part of the message.data. Have a look at the output log:

```
I/flutter (11236): RemoteMessage received while app is in foreground:
I/flutter (11236): RemoteMessage.Notification: null
I/flutter (11236):  body: null
I/flutter (11236): RemoteMessage.Data: {data: {}, notification: {title: Test, body: Test Message}}
...
...
I/flutter (14184): RemoteMessage received while app is in background:
I/flutter (14184): RemoteMessage.Notification: null
I/flutter (14184):  title: null
I/flutter (14184):  body: null
I/flutter (14184): RemoteMessage.Data: {data: {}, notification: {title: Test, body: Test Message}}
```

BTW, it works ok for IOS

**Comment by ianselmi** [comment]
Any news about this problem?
I have the same issue when I sent a notification from Firebase for Android
![image](https://github.com/ben-xD/push/assets/5089542/df609e80-9352-40da-9b36-57340ceb3568)

**Comment by chaau** [comment]
I ended up with this code, not an ideal solution, but it works. Looking forward to getting rid of this workaround:

`
  push.Notification extractNotificationFromMessage(push.RemoteMessage message) {
    late push.Notification notification;
    if (Platform.isAndroid && message.notification == null) {
      var obj;
      if (message.data?["notification"] != null) {
        obj = message.data?["notification"] as Map<Object?, Object?>;
      } else if (message.data?["data"] != null) {
        obj = message.data?["data"] as Map<Object?, Object?>;
        if (obj?["message"] != null) {
          obj = jsonDecode(obj?["message"] as String) as Map<String, Object?>;
        } else if (obj?["default"] != null) {
          obj = jsonDecode(obj?["default"] as String) as Map<String, Object?>;
        }
        obj = obj?["notification"] as Map<String, Object?>;
      }
      notification = push.Notification(title: obj?["title"] as String?, body: obj?["body"] as String?);
      message.notification = notification;
    } else {
      notification = message.notification as push.Notification;
    }
    return notification;
  }
`
