### ISSUE TITLE
[Question] [iOS] Does the operation inside 'onBackgroundMessage' run in background even with app killed?

### ISSUE THREAD

**Issue by mariopepe** [ben-xD/push#3]
First of all WHAT A GREAT PACKAGE!
I am planning to become an advocate for this, so good!!!

I have a question tho, let's take this sample task:

```dart
Push.instance.onBackgroundMessage.listen((message) async {
        final sp = await SharedPreferences.getInstance();
        await sp.setInt('number', 99);
      });
```

So basically, I want to set a certain key in shared preferences to 99.

Let's say I kill the iOS app, so I force quit it (I mean [this](https://www.youtube.com/watch?v=XfXsD_DAuvo) if there is any doubt).

Then I send a notification to my app, everything works nicely and the notification is displayed on the screen and notification center etc.

Now, **my app is still killed**, I did not tap on the notification, I did not tap on the icon of the app.

Should I assume that my shared preferences is being set to 99 while in background? Or that operation above will be performed as soon as I will open the app again?
Thanks a lot!

**Comment by ben-xD** [comment]
Hey @mariopepe, 

If you force quit your app, push notifications won't be delivered to it. Therefore, there is nothing we can do in any app to receive the push notifications. (iOS apps without Flutter, or Flutter with/without this package apps). There a bit more information on https://stackoverflow.com/a/32045542/7365866

**Comment by FynnMazurkiewicz** [comment]
Hi @ben-xD, sorry to be reviving this thread, but I don't understand this part:
> If you force quit your app, push notifications won't be delivered to it. 

Are you saying that *any* iOS app on the planet, can't receive push messages after being force-quit? Because when I force-quit the WhatsApp app on iOS, I still receive push messages immediately, when someone messages me. So that can't be true.

**Comment by ben-xD** [comment]
Oh that's an interesting observation. I noticed Apple removed the documentation I was linking to...

So I tested it. Force quit the push example app, and push notifications are **still delivered**.

## Removed documentation
> In most cases, the system does not relaunch apps after they are force quit by the user. One exception is location apps, which in iOS 8 and later are relaunched after being force quit by the user. In other cases, though, the user must launch the app explicitly or reboot the device before the app can be launched automatically into the background by the system.

**Comment by ben-xD** [comment]
Ahh, but another approach for the past is mentioned on https://stackoverflow.com/a/19202487/7365866:

> You can achieve this using the new PushKit framework, introduced in iOS 8. Though PushKit is used for VoIP. So your usage should be for VoIP related otherwise there is risk of app rejection. (See [this answer](https://stackoverflow.com/a/29231395/2446155)).

**Comment by FynnMazurkiewicz** [comment]
Yea, I also found https://security.stackexchange.com/questions/119624/how-is-whatsapp-sending-end-to-end-encrypted-messages-in-push-notifications, which is a great read - if true.
