### ISSUE TITLE
flutter_local_notification present parameters ignored

### ISSUE THREAD

**Issue by Arley011** [ben-xD/push#32]
Push plugin has some logic to not show APNs notifications received in foreground, but show it if received from `flutter_local_notifications`: 
<img width="1081" alt="Знімок екрана 2023-08-09 о 17 09 38" src="https://github.com/ben-xD/push/assets/51764011/fbb91db2-072b-482a-b028-c957265b4ea1">

 **This logic is fine, but not complete because local notification may have present parameters to not show notification.**  
 For example, in my project we have a scheduled notification that is configured to not show if the app is in the foreground. But after adding `push` plugin it started showing up during foreground.
 I suggest to add a logic to check such parameters:  

![Знімок екрана 2023-08-09 о 17 20 31](https://github.com/ben-xD/push/assets/51764011/3ec841cc-508c-471c-807e-0a675377124a)

I'll try to do so and maybe will create a PR for this amazing plugin.

**Comment by ben-xD** [comment]
Closed by https://github.com/ben-xD/push/pull/33. Thanks for your PR!
