### ISSUE TITLE
iOS, Push.instance.onBackgroundMessage not triggered when app is terminated

### ISSUE THREAD

**Issue by ben-aw** [ben-xD/push#34]
In iOS, when the app is terminated by the user, push notifications can still arrive, but `Push.instance.onBackgroundMessage` is never triggered.

**Comment by ben-aw** [comment]
Closing this as it is the expected behavior on iOS as noted [here](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application)

Excerpt: `However, the system does not automatically launch your app if the user has force-quit it. In that situation, the user must relaunch your app or restart the device before the system attempts to launch your app automatically again.`

**Comment by BeFriendMe-Resources** [comment]
> Closing this as it is the expected behavior on iOS as noted [here](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application)
> 
> Excerpt: `However, the system does not automatically launch your app if the user has force-quit it. In that situation, the user must relaunch your app or restart the device before the system attempts to launch your app automatically again.`

Then how apps like WhatsApp, Messenger work properly even if app is forcefully terminated?

**Comment by delwar36** [comment]
> Closing this as it is the expected behavior on iOS as noted [here](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application)
> 
> Excerpt: `However, the system does not automatically launch your app if the user has force-quit it. In that situation, the user must relaunch your app or restart the device before the system attempts to launch your app automatically again.`

Then how apps like WhatsApp, Messenger works properly even in terminated state?

**Comment by ben-xD** [comment]
Possibly via VoIP notifications from PushKit. See https://developer.apple.com/documentation/pushkit/responding_to_voip_notifications_from_pushkit and https://stackoverflow.com/a/35912009/7365866
