### ISSUE TITLE
APN says "OK" but never receiving the notification in development mode (flutter run)

### ISSUE THREAD

**Issue by georgiosd** [ben-xD/push#39]
Hey guys

I'm wondering if anyone has any suggestions on this issue. 

When we're working locally with `flutter run`, either on a simulator or real device, we need notifications and the APN API will return `200 OK` but the notification is never seen on the device/emulator.

We checked the device logs and there is nothing telling. 

Has anyone had a similar problem and managed to resolve it?

Thanks in advance!

**Comment by ben-xD** [comment]
I'm sorry for the late reply!

Have you tried the send_ios.sh tool https://github.com/ben-xD/push/tree/main/tools/ios to send your device the push notification? Perhaps try the example app to see if that can work.

**Comment by georgiosd** [comment]
I cant remember how or why but we managed to release the app. Not sure if we ever got it working on sim.
