### ISSUE TITLE
Azure Notifications Hub integration

### ISSUE THREAD

**Issue by joaconigro** [ben-xD/push#52]
Hi everyone,

Sorry, I'm new here. Could you point me in the right direction to integrate this library with Azure Notifications Hub. I have a backend written in ASP .NET Core and I want to use this library on my Flutter app. I've followed this guide https://learn.microsoft.com/en-us/previous-versions/azure/developer/mobile-apps/notification-hubs-backend-service-flutter but it looks a bit outdated.

Also, I would like to know how to send a notification to a specific user, not to everyone.

I don't know if this is the right place to ask, but I can't find any documentation besides the README.md

Thank you

**Comment by ben-xD** [comment]
Hey @joaconigro

I have not used Azure Notifications Hub, however I skimmed the docs you linked. [Add dependencies and configure services](https://learn.microsoft.com/en-us/previous-versions/azure/developer/mobile-apps/notification-hubs-backend-service-flutter#add-dependencies-and-configure-services) just shows it templating out an object that it will send either FCM or APNs. It will just send an HTTP request with a JSON body. You need to structure this JSON body correctly, and FCM and APNs will send your messages to your Android and iOS devices respectively.

You send messages in a simpler way using the tools/scripts I have in https://github.com/ben-xD/push/tree/main/tools

**Comment by joaconigro** [comment]
Thank you @ben-xD for your reply. I will take a look to the documentation you provided 🙂.

And I'll close this issue

Thanks!
