### ISSUE TITLE
「question」In iOS, when the App is killed, how to save the message to the App without clicking the notification bar.

### ISSUE THREAD

**Issue by qflbai** [ben-xD/push#56]
Thank the author, and I would like to ask the author a question. In iOS, when the App is killed, the pushed message will be displayed in the notification bar. How can I save the message in the notification bar to the App's database without clicking on the notification bar?

**Comment by ben-xD** [comment]
Hey @qflbai,

I don't think this is possible. The closest way is to send 2 notifications, 1 alert, and 1 background ( [create a background notification](https://developer.apple.com/documentation/usernotifications/pushing-background-updates-to-your-app#Create-a-background-notification)) and listen for background messages `addOnBackgroundMessage` in the [Usage](https://github.com/ben-xD/push/tree/main/push#usage).

As per the [create a background notification](https://developer.apple.com/documentation/usernotifications/pushing-background-updates-to-your-app#Create-a-background-notification) docs:

>  The system treats background notifications as low priority: you can use them to refresh your app’s content, but the system doesn’t guarantee their delivery. In addition, the system may throttle the delivery of background notifications if the total number becomes excessive. The number of background notifications allowed by the system depends on current conditions, but don’t try to send more than two or three per hour.

I find the algorithm to be opaque. It's not clear what conditions prevent the message from being delivered.

**Comment by qflbai** [comment]
thank you

**Comment by mihai-gabriel8** [comment]
Hello @qflbai 

Just pitching in, if you haven't done this already, I manage to do this with Workmanager 

I added task execution in the "addOnBackgroundMessage" handler that saves all the incoming messages (in my case, chat messages) in the local device store even when application is killed

I can provide an example if you still need it
