### ISSUE TITLE
[push_android] Upgrade Kotlin Gradle version

### ISSUE THREAD

**Issue by DouglasOGarrido** [ben-xD/push#8]
Hi, I'm using the latest version of Flutter and Kotlin Gradle version, but unfortunately the version of `push_android` dependency do not satisfy newer versions of Kotlin Gradle plugin.

When i build my project: 
```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':push_android' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50
```

Could you please update the dependencies? Thank you very much.

**Comment by ben-xD** [comment]
Sorry for the delay, I'll try and work on it tonight 🙂

**Comment by ben-xD** [comment]
Sorry for the delay again 😬. Got caught up with other things. Trying now

**Comment by DouglasOGarrido** [comment]
> Sorry for the delay again 😬. Got caught up with other things. Trying now

Not a problem, thank you for the support! 😃 .

**Comment by ben-xD** [comment]
It turned out to be a bigger task (some dependencies had already upgraded to API level 33) so I wanted to get all of that done too. See https://github.com/ben-xD/push/pull/10

I've briefly tested on Android, looks good. A few more things to do.

**Comment by ben-xD** [comment]
Please try 1.0.0 @DouglasOGarrido 🤓
