### ISSUE TITLE
pub get failed

### ISSUE THREAD

**Issue by SelaineSWDev** [ben-xD/push#9]
Any ideas what I am missing?

Pulled down repo, followed readme to "get started"
- Clone project
- Open the push package
- flutter pub get fails:
`$flutter pub get 
Running "flutter pub get" in push...
Resolving dependencies... 
  async 2.10.0 (2.11.0 available)
  characters 1.2.1 (1.3.0 available)
  collection 1.17.0 (1.17.1 available)
  flutter_lints 1.0.4 (2.0.1 available)
  js 0.6.5 (0.6.7 available)
  lints 1.0.1 (2.1.0 available)
  matcher 0.12.13 (0.12.16 available)
  material_color_utilities 0.2.0 (0.5.0 available)
  meta 1.8.0 (1.9.1 available)
  path 1.8.2 (1.8.3 available)
  plugin_platform_interface 2.1.2 (2.1.4 available)
  source_span 1.9.1 (1.10.0 available)
  test_api 0.4.16 (0.5.2 available)
Got dependencies!
Resolving dependencies in ./example... 
Resolving dependencies in ./example failed. For details run `flutter pub get --directory ./example`
pub get failed
command: "/Users/selaine/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --color --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/selaine/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/Users/selaine/.pub-cache",
}
exit code: 1`

Then:

`$flutter pub get --directory ./example 
Could not find an option named "directory".`

**Comment by ben-xD** [comment]
Hey @SelaineSWDev, looks like there was a breaking change in the `pubspec.lock` format, I've tried to fix that in 87233b9b5e4631f6a6019bf8b56c464941ef3507. Please let me know if that fixes it.

**Comment by SelaineSWDev** [comment]
Yes!  I did some digging and found breaking changes in a couple of the dependency packages too

Looks like pub get is resolved!  Thank you!  Will give the example a try.


`$ flutter pub get

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Running "flutter pub get" in push...
Resolving dependencies... 
  async 2.10.0 (2.11.0 available)
  characters 1.2.1 (1.3.0 available)
  collection 1.17.0 (1.17.1 available)
  flutter_lints 1.0.4 (2.0.1 available)
  js 0.6.5 (0.6.7 available)
  lints 1.0.1 (2.1.0 available)
  matcher 0.12.13 (0.12.16 available)
  material_color_utilities 0.2.0 (0.5.0 available)
  meta 1.8.0 (1.9.1 available)
  path 1.8.2 (1.8.3 available)
  plugin_platform_interface 2.1.2 (2.1.4 available)
  source_span 1.9.1 (1.10.0 available)
  test_api 0.4.16 (0.5.2 available)
Got dependencies!
Resolving dependencies in ./example... (1.0s)
Got dependencies in ./example.`
